ignored:
  - DL3013 # warning: Pin versions in pip. Instead of `pip install <package>` use `pip install <package>==<version>` or `pip install --requirement <requirements file>`
  - DL3059 # info: Multiple consecutive `RUN` instructions. Consider consolidation.
  - DL3040 # warning: `dnf clean all` missing after dnf command.
  - DL3041 # warning: Specify version with `dnf install -y <package>-<version>`.