---
# Config file for automatic testing at travis-ci.com

dist: focal
language: python
services: docker
python:
  - 3.8
jobs:
  include:
    - stage: docker-fedora
      name: Test within Fedora Image
      install:
        - docker build -t fedora .
      script:
        - docker run fedora /bin/sh -c "cd /src; make code; make test" --user='user1'

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: "__token__"
  password:
    # Assuming you have installed the travis-ci CLI tool, after you
    # create the Github repo and add it to Travis, run the
    # following command to finish PyPI deployment setup:
    # travis encrypt {PYPI_TOKEN} --add deploy.password -r Iolaum/fcust
    secure: gzlD9qocm0jdtx7xpQC4NE090fSzJWtlu++bBH8ayKe3UNnx+uiLARxoad1ICKcoIhkYvAk2NwdfsjSLPIckrNtc07ZX6c1boV/0zGYxQiQi4d/S6lZt1F5nB9cyQDS2TH772hAge4p6r3dxauOjdrp9aW5kcGJuzxUQkaDBSptGGaK4idF2ShRpKXfERwcDtZdrkLc3haUaLoTMmbMA80l5Cq7Im3sgjma3/y1zV3xFmNhvCwtDbQvPGgYMPMWeKHC7ZAv05JN0TWsUzp61XjvRTneoKgUxWxM4PRJfLl7oYexvWjGEjdtipY1MLJBZsRCDkuafLf/njhoktkCRB6nV7ZW4Lpr847/0hB0cPxEC2LzgL6IImEEe+a5zPh54JzvDZlQN4rA1aR/xuFaUvCy3aJPRxrtqXs6YogAXrPHWX4VgmCHvCPdAQAcTwoBudW2zEruc3u3MtTnuYgppbhr0GonECE+bmHwPLLivDVfl8XZ3kFd5B5pxkTc/8/TilJMIjKfMyrm3zGvC5tgVaYKfAtwHHRKcuGDfUngj0ZRHoe0r3wDGLxOsNcQd8xuMNxwDigQ4DsOV8FSNSYzrx9naSpbuKqJVSPoQMCinX8e/VSrYKgoz+Kc5O/zxITg0JwWLkf+yG7AOrk2jvYkoK3KyWXRyVTqeqmIy+TzFNPU=
  skip_existing: true
  on:
    tags: true
    repo: Iolaum/fcust
    python: 3.8
