name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fcust_ci_job:
    runs-on: ubuntu-latest
    name: Folder Custodian CI Job
    steps:
      - name: fcust-container-ci
        id: hello
        uses: Iolaum/fcust@ghactions
