name: CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  fcust_ci_job:
    runs-on: ubuntu-latest
    name: Folder Custodian CI Job
    steps:
      - name: fcust-container-ci
        id: fcust_ci_step1
        uses: Iolaum/fcust@main
